import Head from "next/head";
import Image from "next/image";
import Footer from "../../Components/Footer/Footer";
import Header from "../../Components/Header/Header";
import Topnav from "../../Components/Topnav/Topnav";
import Faq from "../../Components/Faq/Faq";
import Faq from "./../../Components/Faq/Faq";

export default function faq() {
  return (
    <>
      <Head>
        <title>BridgeTech | Faq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-blue.png" size="64x64" />
      </Head>
      <Topnav />
      <Header />
      <Faq />
      <Footer />
    </>
  );
}
