import Head from "next/head";
import Image from "next/image";
import Footer from "../../Components/Footer/Footer";
import Header from "../../Components/Header/Header";
import Topnav from "../../Components/Topnav/Topnav";

export default function faq() {
  return (
    <>
      <Head>
        <title>BridgeTech | Faq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topnav />
      <Header />
      <h1>Faq</h1>
      <Footer />
    </>
  );
}
