const DataServ = [
  {
    id: 1,
    image: "/images/app3.jpg",
    title: " Mobile Applications",
    urlPath: "/services/mobile-app",
    text: "  Application designed specifically for user on mobile devices such as smartphones & tablets  to provide specific functionalities, services, or experiences to users on their mobile devices. ",
  },
  {
    id: 2,
    image: "/images/web2.jpg",
    title: " Website Development",
    urlPath: "/services/web-development",
    text: " It involves designing, coding, & testing the various components that make up a website, user interface, functionality using  HTML5, CSS3, javascript, Git/Github, Jquery, Bootstrap, CMS & others tools  ",
  },
  {
    id: 3,
    image: "/images/kids.jpg",
    title: "Kids Coding Training",
    urlPath: "/services/web-design-training",
    text: "Bidgekode trains students/Kids interested in learning web design, there are several paths you can take to acquire the crucial skills & knowledge.  ",
  },
  {
    id: 4,
    image: "/images/figma.jpg",
    title: " UI / UX Design",
    urlPath: "/services/ui-ux",
    text: " UX/UI design refers to the process of creating user-centric interfaces for digital products, such as websites, mobile apps, or software applications. ",
  },
  {
    id: 5,
    image: "/images/graphic.jpg",
    title: " Graphics Design",
    urlPath: "/services/graphics-design",
    text: "Graphic design is the art and practice of creating visual content using typography, images, and other graphical elements ",
  },
  {
    id: 6,
    image: "/images/software2.jpg",
    title: "Software Development",
    urlPath: "/services/software-development",
    text: "Designing, coding, testing, and maintaining software apps using technologies like HTML, CSS, Js & js frameworks like React, Next, Vue, Angular & CSS3 frameworks like Chakra, Tailwind.",
  },
  {
    id: 7,
    image: "/images/it-setup.jpg",
    title: "  IT Setup & Management",
    urlPath: "/services/it-setup-mgmt",
    text: " It involves the establishment, maintenance, and administration of information technology infrastructure and systems within an organization.  ",
  },
  {
    id: 8,
    image: "/images/brand-seo.jpg",
    title: " Branding & SEO",
    urlPath: "/services/branding-seo",
    text: " It refers to the practice of optimizing websites, web pages, and online content to improve their visibility and rankings in search engine results pages (SERPs).  ",
  },
  {
    id: 9,
    image: "/images/network2.jpg",
    title: " Hardware & networking",
    urlPath: "/services/hardware-network",
    text: " It encompasses all the tangible parts of a computer  system that you can touch, see & interact with. Ranges from components, internal parts to peripheral devices ",
  },
  {
    id: 10,
    image: "/images/hr.jpg",
    title: " Human Resources(HR)",
    urlPath: "/services/human-resources",
    text: "These department function within an organization that is responsible for managing & overseeing the human capital or workforce. HR plays a crucial role in recruiting, hiring, training, developing, & supporting employees throughout their employment lifecycle.",
  },
  {
    id: 11,
    image: "/images/flask.jpg",
    title: " Python Data-Science",
    urlPath: "/services/python",
    text: "Its widely used in the field of data science due to its  versatility & extensive collection of libraries & frameworks, robust ecosystem of tools specifically designed for data manipulation, analysis, visualization & machine learning ",
  },
  {
    id: 12,
    image: "/images/digital.jpg",
    title: " Digital & Social Media",
    urlPath: "/services/social-media",
    text: "An online platforms & websites that enable users to create, share & interact with contents, connect & communicate with others. It allows individuals & organizations to share information, ideas, opinions, & media in various formats like text, images, videos, & links.  ",
  },
];

export default DataServ;