const DataServ = [
  {
    id: 1,
    image: "/images/project7.jpg",
    title: " Mobile Applications",
    urlPath: "/services/mobile-app",
    text: "  Application designed specifically for user on mobile devices such as smartphones & tablets  to provide specific functionalities, services, or experiences to users on their mobile devices. ",
  },
  {
    id: 2,
    image: "/images/project5.jpg",
    title: " Website Development",
    urlPath: "/services/web-development",
    text: " It involves designing, coding, & maintaining the various components that make up a website, user interface, functionality, & databases ",
  },
  {
    id: 3,
    image: "/images/project10.jpg",
    title: "Web Design Training",
    urlPath: "/services/web-design-training",
    text: " If you're interested in learning web development, there are several paths you can take to acquire the necessary skills and knowledge.  ",
  },
  {
    id: 4,
    image: "/images/project2.jpg",
    title: " UI / UX Design",
    urlPath: "/services/ui-ux",
    text: " UX/UI design refers to the process of creating user-centric interfaces for digital products, such as websites, mobile apps, or software applications. ",
  },
  {
    id: 5,
    image: "/images/project7.jpg",
    title: " Graphics Design",
    urlPath: "/services/graphics-design",
    text: " Graphic design is the art and practice of creating visual content using typography, images, and other graphical elements ",
  },
  {
    id: 6,
    image: "/images/project3.jpg",
    title: "Software Development",
    urlPath: "/services/software-development",
    text: " Software development refers to the process of designing, coding, testing, and maintaining software applications or systems. ",
  },
  {
    id: 7,
    image: "/images/project1.jpg",
    title: "  IT Setup & Management",
    urlPath: "/services/it-setup-mgmt",
    text: " It involves the establishment, maintenance, and administration of information technology infrastructure and systems within an organization.  ",
  },
  {
    id: 8,
    image: "/images/project5.jpg",
    title: " Branding & SEO",
    urlPath: "/services/branding-seo",
    text: " It refers to the practice of optimizing websites, web pages, and online content to improve their visibility and rankings in search engine results pages (SERPs).  ",
  },
  {
    id: 9,
    image: "/images/project10.jpg",
    title: " Hardware & networking",
    urlPath: "/services/hardware-network",
    text: " It encompasses all the tangible parts of a computer or electronic system that you can touch, see, and interact with. Hardware includes a wide range of components, from basic internal parts to peripheral devices ",
  },
  {
    id: 10,
    image: "/images/project7.jpg",
    title: " Human Resources(HR)",
    urlPath: "/services/human-resources",
    text: " These department function within an organization that is responsible for managing & overseeing the human capital or workforce. HR plays a crucial role in recruiting, hiring, training, developing, & supporting employees throughout their employment lifecycle.",
  },
  {
    id: 11,
    image: "/images/project5.jpg",
    title: " Python Data-Science",
    urlPath: "/services/python",
    text: " Language widely used in the field of data science due to its  versatility & extensive collection of libraries & frameworks. Python provides a robust ecosystem of tools & libraries specifically designed for data manipulation, analysis, visualization, & machine learning ",
  },
  {
    id: 12,
    image: "/images/project2.jpg",
    title: " Digital & Social Media",
    urlPath: "/services/social-media",
    text: "  Refers to online platforms & websites that enable users to create, share, & interact with content, as well as connect & communicate with others. It allows individuals & organizations to share information, ideas, opinions, & media in various formats such as text, images, videos, & links.  ",
  },
];

export default DataServ;