const DataServ = [
  {
    id: 1,
    image: "/images/project7.jpg",
    title: " Mobile Applications",
    urlPath: "/services/mobile-app",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 2,
    image: "/images/project5.jpg",
    title: " Website Development",
    urlPath: "/services/web-development",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 3,
    image: "/images/project10.jpg",
    title: "Web Design Training",
    urlPath: "/services/web-design-training",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 4,
    image: "/images/project2.jpg",
    title: " UI / UX Design",
    urlPath: "/services/ui-ux",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 5,
    image: "/images/project7.jpg",
    title: " Graphics Design",
    urlPath: "/services/graphics-design",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 6,
    image: "/images/project3.jpg",
    title: "Software Development",
    urlPath: "/services/software-development",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 7,
    image: "/images/project1.jpg",
    title: "  IT Setup & Management",
    urlPath: "/services/it-setup-mgmt",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 8,
    image: "/images/project5.jpg",
    title: " Branding & SEO",
    urlPath: "/services/branding-seo",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 9,
    image: "/images/project10.jpg",
    title: " Hardware & networking",
    urlPath: "/services/hardware-network",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 10,
    image: "/images/project7.jpg",
    title: " Human Resources(HR)",
    urlPath: "/services/human-resources",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 11,
    image: "/images/project5.jpg",
    title: " Python Data-Science",
    urlPath: "/services/python",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
  {
    id: 12,
    image: "/images/project2.jpg",
    title: " Digital & Social Media",
    urlPath: "/services/social-media",
    text: " Neque porro quisquam est qui most dolorem quia enough impedit same quo minus quod and maxime ",
  },
];

export default DataServ;