const TeamData = [
  {
    id: "1",
    image: "/images/team-ceo.jpg ",
    name: "Ochu Dominic",
    job: "CEO, President",
    profile: "/team/president",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "2",
    image: "/images/digital-head.jpg ",
    name: "Olatunde Sleek",
    job: "Project Manager",
    profile: "/team/promanager",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "3",
    image: "/images/senior-frontend.jpg ",
    name: "Ogada Stanley",
    job: "Senior Frontend Engineer.",
    profile: "/team/frontend",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "4",
    image: "/images/product-designer.jpg ",
    name: "Egaji Samuel",
    job: "Product(UX/UI) Designer",
    profile: "/team/uxui",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "5",
    image: "/images/seo-expert.jpg ",
    name: "Isaac Oti",
    job: "Web/Graphic Designer",
    profile: "/team/graphic",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "6",
    image: "/images/project-man.jpg ",
    name: "Mudashir Tunde",
    job: "FullStack Software Engineer.",
    profile: "/team/fullstack",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "7",
    image: "/images/full-stack.jpg ",
    name: "Owoicho Emma ",
    job: "Branding/SEO Expert",
    profile: "/team/branding",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "8",
    image: "/images/graphic.jpg ",
    name: "Dim Lawrence",
    job: "Hardware/Network Engr",
    profile: "/team/hardware",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "9",
    image: "/images/graphic.jpg ",
    name: "Nwabudike Ifeanyi",
    job: "Admin Officer",
    profile: "/team/admin",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "10",
    image: "/images/full-stack.jpg ",
    name: "Ochu Comfort",
    job: "Junior Copywriter",
    profile: "/team/juniorwriter",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
  {
    id: "11",
    image: "/images/full-stack.jpg ",
    name: "Johnson JnpRof",
    job: "Web Dev Tutor",
    profile: "/team/tutor",
    facebookLink: "https://www.facebook.com/jpRoF.2023",
    instagramLink: "https://instagram.com/jnprof_2022/",
    twitterLink: "https://twitter.com/jpRoF_2023",
    linkedinLink: "http://linkedin.com/in/jprof2023",
  },
  {
    id: "12",
    image: "/images/full-stack.jpg ",
    name: "Esther Uchechi",
    job: " Senior Content Writer",
    profile: "/team/seniorwriter",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/in/",
  },
];
export default TeamData;
