
const TeamData = [
  {
    image: "/images/team-ceo.jpg ",
    name: "Ochu Dominic",
    job: "CEO, President",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/digital-head.jpg ",
    name: "Olatunde Oladipo",
    job: "Project Manager",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/senior-frontend.jpg ",
    name: "Ogada Stanley",
    job: "Senior Frontend Egr.",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/product-designer.jpg ",
    name: "Egajivwie Samuel",
    job: "Product(UX/UI) Designer",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/seo-expert.jpg ",
    name: "Isaac Oti",
    job: "Branding/Graphic Designer",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/project-man.jpg ",
    name: "Mudashir Tunde",
    job: "FullStack Software Egr.",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/full-stack.jpg ",
    name: "Owoicho Emmanuel ",
    job: "SEO Expert",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
  {
    image: "/images/graphic.jpg ",
    name: "Nwabudike Ifeanyi",
    job: "Digital Marketing",
    profile: "View Profile",
    facebookLink: "https://www.facebook.com/",
    instagramLink: "https://www.instagram.com/",
    twitterLink: "https://twitter.com/",
    linkedinLink: "https://linkedin.com/",
  },
];
export default TeamData