import Head from 'next/head'
import Image from 'next/image'
import Header from "../Components/Header/Header";
import Topnav from '../Components/Topnav/Topnav';

export default function Home() {
  return (
    <>
      <Head>
        <title>BridgeTech | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topnav/>
      <Header />
      <h1>Home</h1>
    </>
  );
}
