import Head from 'next/head'
import Image from 'next/image'
import Header from "../Components/Header/Header";
import Topnav from '../Components/Topnav/Topnav';
import Footer from "../Components/Footer/Footer";
import HomePage from "../Components/HomePage/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>BridgeTech | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-blue.png" size="64x64" />
      </Head>
      <Topnav />
      <Header />
      <HomePage />

      <Footer />
    </>
  );
}
